import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as Y from "yjs";
import { WebrtcProvider } from "y-webrtc";

export default function Home() {
  const [chat, setChat] = useState([]);
  const [yd, setYdoc] = useState(null);
  const [msg, setMsg] = useState("");
  useEffect(() => {
    const ydoc = new Y.Doc();
    const provider = new WebrtcProvider("your-room-name", ydoc, {
      password: "optional-room-password",
    });
    const ymap = ydoc.getMap("state", Y.Array);
    ymap.observe(() => {
      console.log("change");
      setChat([...ymap.get("state")]);
    });
    setYdoc(ydoc);
  }, []);

  const send = () => {
    console.log(yd);
    const s = yd.getMap("state");
    s.set("state", [...chat, msg]);
  };

  const clear = () => {
    const s = yd.getMap("state");
    s.set("state", []);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={() => {}}>
        <input
          type="text"
          value={msg}
          onChange={(e) => setMsg(e.target.value)}
        />
        <button onClick={send}>Send</button>
        <button onClick={clear}>Clear</button>
      </form>
      {chat.map((msg, i) => (
        <div key={i}>{msg}</div>
      ))}
    </div>
  );
}
